[package]
name = "pelin"
version = "0.1.0"
edition = "2021"

[lib]
name = "pelin"
path = "src/lib.rs"

[[bin]]
name = "pelin"
path = "src/main.rs"

[dependencies]
env_logger = "0.11.5"
libloading = "0.8.5"
log = "0.4.22"
pretty_assertions = "1.4.1"
rustyline = "14.0.0"
tempfile = "3.13.0"
